# Generated by Django 3.1.3 on 2020-11-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=120, null=True)),
                ('count', models.BigIntegerField(blank=True, null=True)),
                ('percent', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
            ],
        ),
    ]
