# Generated by Django 3.1.3 on 2020-11-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_auto_20201108_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='percent_human',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True),
        ),
    ]
