# Generated by Django 3.1.3 on 2020-11-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_topic_percent_human'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='percent_human',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
