# Generated by Django 3.1.3 on 2020-11-08 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_auto_20201108_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='percent_human',
        ),
    ]
