# Generated by Django 3.1.3 on 2020-11-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_remove_topic_percent_human'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='percent_human',
            field=models.TextField(blank=True, null=True),
        ),
    ]
