# Generated by Django 3.1.3 on 2020-11-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0006_topic_percent_human'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='percent_human',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
